### ISSUE TITLE
Collection Helpers compatibility?

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#32]
I just wanted to know if ReactRouterSSR was compatible with [dburles:collection-helpers](https://github.com/dburles/meteor-collection-helpers)?

Since SSR fakes data using a LocalCollection that doesn't support helpers, I guess not, but I was wondering if there might be a way of injecting the helpers server side?

**Comment by dbismut** [comment]
There might be a way using [dburles:mongo-collection-instances](https://github.com/dburles/mongo-collection-instances).

I'm pretty sure this is super ugly, but I tried the below and it works.

```javascript
// server.js L368

Mongo.Collection._ssrData[name] = new LocalCollection(name);
const originalFind = Mongo.Collection._ssrData[name].find;
Mongo.Collection._ssrData[name].find = function(selector, options) {
  _.extend(options, {transform: (doc) => Mongo.Collection.get(name)._transform(doc)});
  return originalFind.call(Mongo.Collection._ssrData[name], selector, options);
}
```

**Comment by dbismut** [comment]
Ok, I think I'm on something better, without `dburles:mongo-collection-instances`.

```javascript
Mongo.Collection.prototype.find = function(...args) {

  if (!Mongo.Collection._isSSR) {
    return originalFind.apply(this, args);
  }

  const newTransform = typeof this._transform === 'function' ? {transform: (doc) => this._transform(doc)} : null;
  const selector = args.length === 0 ? {} : args[0];
  let options = args.length < 2 ? {} : args[1];

  if (newTransform) {
    options = {...options, ...newTransform};
  }

  return this._getSSRCollection().find(selector, options);
};
```

And the same for `Mongo.Collection.prototype.find`. This seems to work somehow for now, @eXon what do you think? Maybe there's another way?

**Comment by dbismut** [comment]
Ok well... This might have been obvious, but even if this works ok, I'm using it with `redux`, and when the server inject the server state to the client, it stringifies the state, and loses the helpers (right @yched ?). I'm pretty sure it's not very `redux` anyway to have object with functions as state attributes.

One way to make it work would be to use [some special JSON parser that is able to stringily and parse functions like this one](https://github.com/vkiryukhin/jsonfn), but it uses eval, I'm not sure this is super safe.

So hey well, no `collection-helpers` for SSR and redux... @eXon, I will let you check if adding the transform function has any sense...

Voilà.

**Comment by yched** [comment]
First , about meteor-react-router-ssr & collection transforms (I'll reply about the redux side in a separate comment)

I didn't get a chance to try meteor-react-router-ssr with collection-helpers so far, but I'd think it would be worthwhile on its own to make sure the "server-side collection stubs" code in meteor-react-router-ssr is compatible with collection transforms (whether defined explicitly or through or collection-helpers) - if that's not the case ATM that seems like a missing feature in meteor-react-router-ssr that would be beneficial for all, independantly of redux use.

I didn't check if the code in the [comment above](https://github.com/thereactivestack/meteor-react-router-ssr/issues/32#issuecomment-173980356) does make it work (if it does, it seems it could still be streamlined a litlle, to something like simply `if (typeof this._transform === 'function') {options.transform = this._transform;}` ?)

IMO that could be a PR on its own, what do you think @eXon ?

**Comment by yched** [comment]
Then about the redux state rehydration feature : as mentioned above, I didn't try meteor-react-router-ssr / redux with collection transforms, so the following is just untested ramblings, opend for discussion.

Yeah, right now the redux supporting code in meteor-react-router-ssr does JSON.stringify() on the server / JSON.parse() on the client, which means that if your state contains documents fetched from your collections, they get downcasted to POJOs before being passed to the client, losing the prototype methods that might have been attached.

AFAIK, that's a known / common behavior with redux server-to-client rehydration, it's up to the client-side code to take care of re-upcasting the raw initial data received from the server to the relevant domain structures where needed.

- You might code this massaging inside the createReduxStore(initialState, history) callback you provide in ReactRouterSSR.Run() options, but that assumes it knows the structure of the reducers, which is not  ideal in terms of separation of concerns (and breaks next time you reorganize your reducer tree)

- It's probably best to have the relevant reducers themselves take care of that upcasting, taking advantage of the fact that redux's createStore() always initially dispatches an internal action with the initialState that was passed to it - in our case the raw state coming from SSR.
 For example in the case of ImmutableJS structures, https://github.com/indexiatech/redux-immutablejs 's createReducer() provides a `constructor` param that does exactly that : upcast an incoming POJO state into an Immutable structure.
  In our case here of a reducer storing documents from a collection that has a transform, I guess that would mean having the reducer check if the incoming state is in the transformed state ("does it have the expected prototype ?"), and if not apply the transformation to it. 
  That could be something like :
  ````js
  function myReducer(state = {}, action) {
    // If needed, upcast the raw state passed by the server SSR. 
    if (typeof state.expectedHelper === 'undefined') { // Or some other check for MyDomainClass ?
      state = transform(state); // Where transform is the same transform you assigned to your collection
    }
    // Then the usual action matching :
    switch (action.type) {
      ...
    }
  }
  ```
  Not exactly sure how that could be written with the implicit transforms declared using collection-helpers :-)

**Comment by dbismut** [comment]
@yched of course, you're code is indeed simpler 👍

**Comment by dbismut** [comment]
@yched thanks for the taking the time of clarifying all this. Very instructive as usual.

The only thing that worries me a bit is reattaching helpers to a full range of objects returned from a fetch query. That would mean restoring the helpers for each object one by one...?

I guess stringifiying and parsing the state in a way that would preserve the methods attached is out of the question?

Anyway, I ended up removing the collection helpers and using helpers functions that take the object as an argument.

**Comment by yched** [comment]
> The only thing that worries me a bit is reattaching helpers to a full range of objects returned from a fetch query. That would mean restoring the helpers for each object one by one...?
Yes, but isn't that basically what a collection with a transform does anyway ? Rerunning the transform on each raw document returned by fetch() / findOne() ?
Here you reducer runs the transform on the raw docs it receives in the initial state - that happens only once on client initialization, after that, it's your collection that's going to apply the transform on each focument that your app's runtime fetches from the minimongo.

It does mean that there are two places that need to be aware of / apply the transform: 1) you collection definition 2) your reducers that store documents in the redux state.
That's because those are the two places that deal with raw documents : 1) the ones read from your  collections, 2) the ones passed in the initialState sent from the server.

> I guess stringifiying and parsing the state in a way that would preserve the methods attached is out of the question?
I guess something like https://github.com/yahoo/serialize-javascript, that is able to serialize functions in a JSON superset, could be investigated, but I'm not sure that's a great idea :
- Means the serialized state passed to the client in the server-sent HTML contains functions body duplicated for *each* document contained in your state, that seems like a lot of bloat to send down the wire
- Not even sure if this at all works with helper functions that call out to other functions in your code base...
- Passing code as strings through the wire to reinstanciate runtime JS functions on the client side seems... icky ?
It seems much better than the server and client side exchange raw data and rely on a common understanding to attach semantics / behavior to that data, i.e run the transform to upcast to a domain object with methods - but I'd think those methods are better off defined by *both* the client and the server code (typicaly with Meteor, in shared code), rather than "passed by the server down the client's throat" ?

I know Meteor's EJSON format allows serializing and unserializing custom data types, but that still requires manual work to define the handlers for those custom types, so that still adds some boilerplate you need to take care of, so I'm not sure this would buy us much compared to the "upcast in the reducer" approach. Also, as discussed in the original ["redux for meteor-react-router-ssr" PR](https://github.com/thereactivestack/meteor-react-router-ssr/pull/24#issuecomment-166969073), using EJSON's stringify() had the big drawback of breaking when the redux store contains ImmutableJS structures :-/

**Comment by dbismut** [comment]
Crystal clear. Thanks for taking the time @yched.

**Comment by yched** [comment]
@dbismut : a PR to support collection transforms in meteor-react-router-ssr still seems like a great idea ;-)

Also, @eXon, I can try to summarize the "upcast domain data in your reducers" approach above in a PR for the readme if you folks think it's a right approach to recommend ?

**Comment by dbismut** [comment]
@yched wow, I never did a pull request for a real open source project 😆

I think it would be interesting to open an issue to list fully or partially incompatible meteor packages (such as publish-composite which doesn't work with SSR).

**Comment by yched** [comment]
@dbismut seems like an excellent opportunity to start ? :innocent:

**Comment by dbismut** [comment]
Just for reference, it seems like [CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS) doesn't work server-side without the use of collection transforms.

**Comment by minfawang** [comment]
Hi @dbismut. Thanks for the update! Does the PR above also apply to transform problem with CollectionFS?

**Comment by dbismut** [comment]
Yes, it should solve it. To be clear, without the PR, you would not be able to call anything like `image.url()` or `image.uploadProgress()` server-side.

However, if you use redux, you need to be careful in **not** storing a FS File object in your state: the server will not be able to parse the object because of circular references. Here's what I'm doing atm:

```javascript
Images.find( { } ).map( d => ({
  _id: d._id,
  uploadProgress: d.uploadProgress()
  url: d.url()
}) );
```

That flattens the objects and make them serializable.

**Comment by minfawang** [comment]
Thanks for the super clear clarification!! The redux part is definitely an easy pitfall although I'm not storing the FS object directly in redux currently.

**Comment by eXon** [comment]
The PR has been merged so I'm closing this. Thank you for your help!
