### ISSUE TITLE
Documentation: Router wrapper; Accept: text/html required; html dom ID and app placement

### ISSUE THREAD

**Issue by yourcelf** [thereactivestack/meteor-react-router-ssr#4]
A couple of things could be documented a bit better -- I spent a while figuring these out:
 - In contrast to ``reactrouter:react-router``, One shouldn't provide a ``<Router>`` wrapper -- this gets constructed by ``ReactRouterSSR``.
 - In order for rendering to work, the client needs to send an explicit ``Accept: text/html`` header.  This means that if you try to check if it's working using a simple ``curl -L localhost:3000`` like I was, it'll appear to not be working.  With curl you'd need ``curl -H 'Accept: text/html' -L localhost:3000`` instead.  It's worth researching whether this negatively impacts e.g. GoogleBot, which may only send [``Accept: */*``](http://googlewebmastercentral.blogspot.com/2008/03/first-date-with-googlebot-headers-and.html), which means it won't index pages unless it parses the javascript.
 - The react app will be placed in a ``<div id='react-app'></div>`` just after the opening ``<body>`` tag, which may or may not be what you expect.  It doesn't appear possible to customize where the app is rendered to within a template when using SSR right now, and the DOM id ``react-app`` is reserved by ReactRouterSSR.  (You might consider changing this to something more unlikely to be a name collision, like ``react-router-ssr-auto-id`` or something).

**Comment by eXon** [comment]
Thank you for the feedback. 

- For the Router wrapper, I added a notice (a single letter isn't obvious I guess)
- For the Accept header, the ReactRouterSSR doesn't touch it. Have you compared with a regular application and seen a difference?
- I added an option for the react-app id (it was planned but never made before). I personally don't think react-app is that but, there is very little chance somebody is using it inside his application. However, it has to be directly inside the body because at the point I inject HTML their is nothing there yet (no Blaze template nothing).

**Comment by eXon** [comment]
- A single letter is kinda hard to figure out I know. I've added a notice in the readme.
- Have you checked if the Accept header is different when not using ReactRouterSSR? It is not suppose to touch any header.
- An client option `rootElement` has been added (it was planned). I can't let you choose where to put it however because of the way it works. The page is still an empty body at the stage we inject the HTML.

**Comment by yourcelf** [comment]
Thanks for the quick response.  The issue is with the client's request headers, not the response header.  See https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/server.jsx#L23-L25:

    // we only need to support HTML pages only
    // this is a check to do it
    return /html/.test(req.headers['accept']);

If the client doesn't provide an ``Accept`` header that includes the string ``html`` within it when requesting a page, ReactRouterSSR skips out and does not inject the app into the page.  This is presumably to avoid munging e.g. stylesheets or images; but this check fails to account for clients that send wildcards as their accept header, e.g. ``Accept: */*``, or clients that omit the header entirely.  It'd be ideal to find another way to filter which pages to inject the app into rather than relying on the not-necessarily-reliable request ``Accept`` header.

**Comment by eXon** [comment]
Oh I see. I need to find a more efficient way to detect if it is an asset or regular page request. This was a copy/paste of how Meteor was doing it. There is probably a better way now.
