### ISSUE TITLE
Make setting the routes more flexible

### ISSUE THREAD

**Issue by RonaldV** [thereactivestack/meteor-react-router-ssr#7]
At the moment defining the routes doesn't exactly follow the react router configuration. Also if you want to wrap the router, you won't be able to.
You could solve this by passing a createRoutes function instead. 
For example:
```javascript
ReactRouterSSR.Run((history, props) => {
return (<Router history={history}
        {...props}>
    <Route path="/" component={App}>
        <IndexRoute component={HomePage} />
        <Route path="login" component={LoginPage} />
        <Route path="*" component={NotFoundPage} />
        {/* ... */}
     </Route>
</Router>);
});
```

What do you think?

**Comment by eXon** [comment]
Hey Ronald, thank you for asking. Your syntax looks cool.

The problem we will face by following this syntax is the Router is not the same on the server and on the client. I would rather keep it as simple as possible, especially because the default settings are fine 90% of the time.

If you look at the options available on the readme, you already got what you need:
```javascript
ReactRouter.Run(
    <Route path="/" component={App}
        <IndexRoute component={HomePage} />
        <Route path="login" component={LoginPage} />
        <Route path="*" component={NotFoundPage} />
  </Route>, {
    history: new ReactRouter.history.createHashHistory(),
    props: { propOnClient: true }
});
```

Do you feel like it fits your need?

**Comment by RonaldV** [comment]
At the moment I don't think I have a need for it (or undecided). I did need it when testing some Flux libraries in Meteor, but I'm not sure I'm going to use them when using Meteor.
For example Flummox and Redux ideally would wrap the Router. That would be a `<Provider store="store"><Router>...`in case of Redux. 
That got me thinking that I might need to wrap the Router for some other reasons in the future.

**Comment by eXon** [comment]
I think it would make sense to create a redux-router-ssr. That way react-router will be plugged with redux. There is some major difference.

I haven't made it because Flux has little to no value to Meteor. I love Redux and use it in other projects but haven't found a rational reason to use it inside Meteor. Subscriptions / minimongo / call are much easier to use. For the few states you need to share, I use the context.

**Comment by RonaldV** [comment]
I think that is fair. As I don't have a use case for it with plain meteor, I'll close this issue.
Thanks for the great package btw.
