### ISSUE TITLE
Question: use react-komposer with redux

### ISSUE THREAD

**Issue by ansonla3** [thereactivestack/meteor-react-router-ssr#79]
I have a question how to integrate with react-komposer with reduce using this meteor-react-router-ssr

I saw there is an example, but I do not understand how is it process.

`import configureStore from './store';  <--- what is insider configureStore function
`
// Pass the state of the store as the object to be dehydrated server side
`const dehydrateHook = () => store.getState();
`
// Take the rehydrated state and use it as the initial state client side
`const rehydrateHook = state => initialState = state;
`
// Create a redux store and pass into the redux Provider wrapper
```
const wrapperHook = app => {
  store = configureStore(initialState, history);
  return <Provider store={store}>{app}</Provider>;
}

```
What is dehydrateHook & rehydrateHook ? Why do we need it? 

Could anyone provide an example ? 

Thanks very much!

**Comment by NickDubelman** [comment]
I too am having trouble getting Redux to work. I'm mostly wondering what configureStore looks like. Clearly it must be a function, so it can't be an exported call to createStore. It also doesn't seem like it should be a call to createStore itself because we are passing it an initialState and history, rather than a reducer.

Also (and I apologize if this is a dumb question but it wasn't clear to me from the example given): do the let declarations in the example need to be replaced with our store, history, and initial state, or should they actually be just empty declarations? It seems like they should be replaced but the actual store that we are passing to Provider is the one returned by configStore, so it's not really clear to me what's going on. 

Any help is appreciated.

**Comment by NickDubelman** [comment]
I don't think you need to use react-router-redux unless you want to sync app state with history.

**Comment by ansonla3** [comment]
ok, thanks very much..!
